### PR TITLE
Updates Tamaraw cover

### PR DESCRIPTION
**Pull request by n0um3n4**
The Tamaraw cover is finally here.

### CODE REVIEW

**Review by mayra-cabrera — COMMENTED** [review]
Love it!!!! 

Do you think we can play a little with buffalo + gopher combination? Maybe adding a gopher to the image,  something like
 


Here's the [source](https://github.com/shalakhin/gophericons/blob/master/png/18.png)

**Review by mayra-cabrera — APPROVED** [review]

**Comment by mayra-cabrera** [comment]
By all means feel free to merge this if you want to :)

**Comment by n0um3n4** [comment]
You mean add gopher buffaloboy (cowboy) or completely remove Tamaraw and just the cowboy?

**Comment by mayra-cabrera** [comment]
gopher + Tamaraw ... maybe a gopher riding Tamaraw? 🤔

**Comment by n0um3n4** [comment]
HAHAH gotcha! so then, first I update the cover, then the merge.

**Pull request closed without merging**
